sudo: false

language: php

php:
    - 7.0
    - 7.1

notifications:
    email: false

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    - composer install --dev
    - npm install -g stylelint

script:
    - phpunit
    - stylelint 'assets/scss/**/*.scss' 'assets/css/*.css'
