---
defaults: &defaults
  docker:
    - image: greenpeaceinternational/circleci-base:latest
  working_directory: /home/circleci/app

version: 2

job-references:
  setup_environment: &setup_environment
    name: "Setup Environment Variables"
    command: |
      source /home/circleci/.bashrc

jobs:
  lint:
    <<: *defaults
    docker:
      - image: greenpeaceinternational/p4-unit-tests:php7.3-develop
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run: *setup_environment
      - run:
          name: "stylelint"
          when: always
          command: stylelint "$HOME/app/src/scss/**/*.scss" "$HOME/app/theme/kss-assets/css/*.scss"

  deploy-dev:
    <<: *defaults
    environment:
      GOOGLE_PROJECT_ID: planet4-production
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run: activate-gcloud-account.sh
      - run: docker-login.sh
      - run: make -C deploy checkout-master
      - run: make -C deploy build
      - run: make -C deploy docker-push
      - run: make -C deploy dev

  deploy-tag:
    <<: *defaults
    environment:
      GOOGLE_PROJECT_ID: planet4-production
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run: activate-gcloud-account.sh
      - run: docker-login.sh
      - run: make -C deploy checkout-tag
      - run: make -C deploy build
      - run: make -C deploy docker-push
      - run: make -C deploy prod

workflows:
  version: 2
  test:
    jobs:
      - lint
  dev:
    jobs:
      - deploy-dev:
          context: org-global
          filters:
            branches:
              only: master
  tag:
    jobs:
      - deploy-tag:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
