---
version: 2.1

defaults: &defaults
  docker:
    - image: greenpeaceinternational/circleci-base:latest
      auth: &docker_auth
  working_directory: /home/circleci/app

job-references:
  docker_auth: &docker_auth
    username: $DOCKERHUB_USERNAME
    password: $DOCKERHUB_PASSWORD

  setup_environment: &setup_environment
    name: "Setup Environment Variables"
    command: |
      source /home/circleci/.bashrc

jobs:
  lint:
    <<: *defaults
    docker:
      - image: greenpeaceinternational/p4-unit-tests:nodelts
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run: *setup_environment
      - run:
          name: "stylelint"
          when: always
          command: stylelint "$HOME/app/src/**/*.scss"

  promote:
    <<: *defaults
    steps:
      - run:
          name: Configure git
          command: |
            mkdir -p ~/.ssh
            echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
            ' >> ~/.ssh/known_hosts
      - run:
          name: Release
          command: |
            mkdir -p /tmp/workspace
            cd /tmp/workspace
            trigger-build.sh git@github.com:${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} tag

  repositories:
    <<: *defaults
    steps:
      - run:
          name: Configure git
          command: |
            mkdir -p ~/.ssh
            echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
            ' >> ~/.ssh/known_hosts
      - run:
          name: Bump styleguide
          command: bump-styleguide.sh

workflows:
  branch:
    jobs:
      - lint
      - promote:
          context: org-global
          filters:
            branches:
              only: master
      - repositories:
          context: org-global
          requires:
            - promote
          filters:
            branches:
              only: master
